/**
 * Generates TypeScript type definitions from translation keys.
 */
export function generateTypes(keys: string[]): string {
	const sortedKeys = [...keys].sort();

	const lines = [
		'// Auto-generated by @edgecms/sdk - do not edit manually',
		'// Run `edgecms pull` to regenerate this file',
		'',
		'export interface TranslationKeys {',
	];

	for (const key of sortedKeys) {
		// Escape quotes in key names
		const escapedKey = key.replace(/"/g, '\\"');
		lines.push(`  "${escapedKey}": string;`);
	}

	lines.push('}');
	lines.push('');
	lines.push('export type TranslationKey = keyof TranslationKeys;');
	lines.push('');
	lines.push('/**');
	lines.push(' * Helper function to get a typed translation key.');
	lines.push(' * This ensures the key exists at compile time.');
	lines.push(' */');
	lines.push('export function t(key: TranslationKey): TranslationKey {');
	lines.push('  return key;');
	lines.push('}');
	lines.push('');

	return lines.join('\n');
}
