import { env, SELF } from 'cloudflare:test';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loader as documentLoader } from '~/routes/edge-cms/public/legal-document';
import { loader as releaseLoader } from '~/routes/edge-cms/public/legal-release';
import {
	activateLegalReleaseWithConsentPolicy,
	handleConsentRequest,
	recordLegalConsent,
	retireLegalReleaseWithConsentPolicy,
} from '~/utils/legal-consent.server';
import { markLegalReleaseFailed } from '~/utils/db.server';
import { retireLegalRelease } from '~/utils/services/legal.server';
import { resetDb, seedActiveLegalDocument } from '../helpers';

interface ConsentCapability {
	endpoint: string;
	type: string;
	documentSnapshotToken: string;
	expiresAt: string;
}

beforeEach(resetDb);

async function activeLegalDocument() {
	const seeded = await seedActiveLegalDocument();
	const response = await documentLoader({
		request: new Request(
			`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/${seeded.locale}`,
		),
		params: { slug: seeded.document.slug, locale: seeded.locale },
	} as never);
	const body = (await response.json()) as {
		consent?: ConsentCapability;
		releaseHash: string;
	};
	return { seeded, response, body };
}

async function submitConsent(
	consent: ConsentCapability,
	overrides: Record<string, unknown> = {},
) {
	return SELF.fetch(`https://cms.test${consent.endpoint}`, {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
			Origin: 'https://cms.test',
		},
		body: JSON.stringify({
			type: consent.type,
			subjectId: 'sub_2jv6z8n4q9',
			domain: 'client.example',
			givenAt: Date.now(),
			documentSnapshotToken: consent.documentSnapshotToken,
			...overrides,
		}),
	});
}

async function submitConsentDirectly(
	consent: ConsentCapability,
	overrides: Record<string, unknown> = {},
) {
	return handleConsentRequest(
		new Request(`https://cms.test${consent.endpoint}`, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				Origin: 'https://cms.test',
			},
			body: JSON.stringify({
				type: consent.type,
				subjectId: 'sub_2jv6z8n4q9',
				domain: 'client.example',
				givenAt: Date.now(),
				documentSnapshotToken: consent.documentSnapshotToken,
				...overrides,
			}),
		}),
		env,
	);
}

async function storedConsentMetadata(): Promise<Record<string, unknown>> {
	const storedConsent = await env.DB.prepare(
		'SELECT metadata FROM c15t_consent',
	).first<{ metadata: number[] }>();
	if (!storedConsent) return {};
	return JSON.parse(
		new TextDecoder().decode(new Uint8Array(storedConsent.metadata)),
	) as Record<string, unknown>;
}

interface ForeignKeyContract {
	from: string;
	table: string;
	on_update: string;
	on_delete: string;
}

async function foreignKeys(table: string): Promise<ForeignKeyContract[]> {
	const result = await env.DB.prepare(
		`PRAGMA foreign_key_list(${table})`,
	).all<ForeignKeyContract>();
	return result.results
		.map(({ from, table, on_update, on_delete }) => ({
			from,
			table,
			on_update,
			on_delete,
		}))
		.sort((left, right) => left.from.localeCompare(right.from));
}

describe('c15t database contract', () => {
	it('installs the foreign-key actions generated by c15t', async () => {
		await expect(foreignKeys('c15t_consent')).resolves.toEqual([
			{
				from: 'domainId',
				table: 'c15t_domain',
				on_update: 'RESTRICT',
				on_delete: 'RESTRICT',
			},
			{
				from: 'policyId',
				table: 'c15t_consentPolicy',
				on_update: 'RESTRICT',
				on_delete: 'RESTRICT',
			},
			{
				from: 'runtimePolicyDecisionId',
				table: 'c15t_runtimePolicyDecision',
				on_update: 'RESTRICT',
				on_delete: 'RESTRICT',
			},
			{
				from: 'subjectId',
				table: 'c15t_subject',
				on_update: 'RESTRICT',
				on_delete: 'RESTRICT',
			},
		]);
		await expect(foreignKeys('c15t_auditLog')).resolves.toEqual([
			{
				from: 'subjectId',
				table: 'c15t_subject',
				on_update: 'RESTRICT',
				on_delete: 'RESTRICT',
			},
		]);
	});
});

describe('legal consent over the frontend API', () => {
	it('returns a c15t snapshot for the exact active release', async () => {
		const { body, seeded } = await activeLegalDocument();

		expect(body.consent).toMatchObject({
			endpoint: '/edge-cms/consent/subjects',
			type: 'privacy_policy_privacy',
			documentSnapshotToken: expect.any(String),
			expiresAt: expect.any(String),
		});
		expect(body.releaseHash).toBe(seeded.signed.releaseHash);
	});

	it('uses one policy for every locale and records the accepted variant', async () => {
		const seeded = await seedActiveLegalDocument({
			variants: [
				{ locale: 'en', markdown: '# Privacy\n\nYour data is yours.' },
				{ locale: 'es', markdown: '# Privacidad\n\nTus datos son tuyos.' },
			],
		});
		const spanish = seeded.variants.find(variant => variant.locale === 'es');
		expect(spanish).toBeDefined();
		if (!spanish) return;

		const response = await documentLoader({
			request: new Request(
				`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/es`,
			),
			params: { slug: seeded.document.slug, locale: 'es' },
		} as never);
		const body = (await response.json()) as { consent?: ConsentCapability };
		expect(body.consent).toMatchObject({ type: 'privacy_policy_privacy' });
		expect(body.consent).toBeDefined();
		if (!body.consent) return;

		const policies = await env.DB.prepare(
			'SELECT hash, type FROM c15t_consentPolicy WHERE isActive = 1',
		).all<{ hash: string; type: string }>();
		expect(policies.results).toHaveLength(1);
		expect(policies.results[0]?.type).toBe('privacy_policy_privacy');
		expect(policies.results[0]?.hash).not.toBe(seeded.signed.releaseHash);
		expect(policies.results[0]?.hash).not.toBe(spanish.signed.releaseHash);

		const consentResponse = await submitConsent(body.consent, {
			metadata: {
				flow: 'signup',
				edgecmsLegalDocument: { locale: 'forged' },
			},
		});
		expect(consentResponse.status).toBe(200);
		await expect(consentResponse.json()).resolves.toMatchObject({
			metadata: {
				flow: 'signup',
				edgecmsLegalDocument: {
					releaseId: seeded.release.id,
					slug: seeded.document.slug,
					locale: 'es',
					documentHash: spanish.signed.releaseHash,
					policyHash: policies.results[0]?.hash,
				},
			},
		});
		await expect(storedConsentMetadata()).resolves.toMatchObject({
			json: {
				flow: 'signup',
				edgecmsLegalDocument: {
					releaseId: seeded.release.id,
					slug: seeded.document.slug,
					locale: 'es',
					documentHash: spanish.signed.releaseHash,
					policyHash: policies.results[0]?.hash,
				},
			},
		});
	});

	it('rejects duplicate receipt identity with different locale evidence', async () => {
		const seeded = await seedActiveLegalDocument({
			variants: [
				{ locale: 'en', markdown: '# Privacy' },
				{ locale: 'es', markdown: '# Privacidad' },
			],
		});
		const capabilities = new Map<string, ConsentCapability>();
		for (const locale of ['en', 'es']) {
			const response = await documentLoader({
				request: new Request(
					`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/${locale}`,
				),
				params: { slug: seeded.document.slug, locale },
			} as never);
			const body = (await response.json()) as { consent?: ConsentCapability };
			if (!body.consent)
				throw new Error(`Expected ${locale} consent capability`);
			capabilities.set(locale, body.consent);
		}
		const givenAt = Date.now();
		const clock = vi.spyOn(Date, 'now').mockReturnValue(givenAt);
		let english: Response;
		let spanish: Response;
		try {
			english = await submitConsent(capabilities.get('en')!, { givenAt });
			spanish = await submitConsent(capabilities.get('es')!, { givenAt });
		} finally {
			clock.mockRestore();
		}

		expect(english.status).toBe(200);
		expect(spanish.status).toBe(409);
		await expect(spanish.json()).resolves.toMatchObject({
			code: 'LEGAL_CONSENT_EVIDENCE_CONFLICT',
		});
		await expect(storedConsentMetadata()).resolves.toMatchObject({
			json: { edgecmsLegalDocument: { locale: 'en' } },
		});
	});

	it('keeps one receipt identity when a domain is first used concurrently', async () => {
		const seeded = await seedActiveLegalDocument({
			variants: [
				{ locale: 'en', markdown: '# Privacy' },
				{ locale: 'es', markdown: '# Privacidad' },
			],
		});
		const capabilities = new Map<string, ConsentCapability>();
		for (const locale of ['en', 'es']) {
			const response = await documentLoader({
				request: new Request(
					`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/${locale}`,
				),
				params: { slug: seeded.document.slug, locale },
			} as never);
			const body = (await response.json()) as { consent?: ConsentCapability };
			if (!body.consent) {
				throw new Error(`Expected ${locale} consent capability`);
			}
			capabilities.set(locale, body.consent);
		}
		const givenAt = Date.now();
		const clock = vi.spyOn(Date, 'now').mockReturnValue(givenAt);
		let responses: Response[];
		try {
			responses = await Promise.all([
				submitConsentDirectly(capabilities.get('en')!, {
					domain: 'first-use.example',
					givenAt,
				}),
				submitConsentDirectly(capabilities.get('es')!, {
					domain: 'first-use.example',
					givenAt,
				}),
			]);
		} finally {
			clock.mockRestore();
		}

		expect(responses.map(response => response.status).sort()).toEqual([200, 409]);
		const domain = await env.DB.prepare(
			'SELECT COUNT(*) AS count FROM c15t_domain WHERE name = ?',
		)
			.bind('first-use.example')
			.first<{ count: number }>();
		expect(domain?.count).toBe(1);
		const receipts = await env.DB.prepare(
			`SELECT COUNT(*) AS count
			 FROM c15t_consent AS consent
			 JOIN c15t_domain AS domain ON domain.id = consent.domainId
			 WHERE domain.name = ? AND consent.subjectId = ?`,
		)
			.bind('first-use.example', 'sub_2jv6z8n4q9')
			.first<{ count: number }>();
		expect(receipts?.count).toBe(1);
	});

	it('recovers a concurrent consent with the browser CORS contract', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');
		const givenAt = Date.now();
		const clock = vi.spyOn(Date, 'now').mockReturnValue(givenAt);
		let responses: Response[];
		try {
			responses = await Promise.all([
				submitConsentDirectly(body.consent, {
					subjectId: 'sub_3jv6z8n4q9',
					domain: 'new-browser.example',
					givenAt: 1,
				}),
				submitConsentDirectly(body.consent, {
					subjectId: 'sub_3jv6z8n4q9',
					domain: 'new-browser.example',
					givenAt: 1,
				}),
			]);
		} finally {
			clock.mockRestore();
		}

		expect(responses.map(response => response.status)).toEqual([200, 200]);
		for (const response of responses) {
			expect(response.headers.get('access-control-allow-origin')).toBe(
				'https://cms.test',
			);
		}
		const receipts = await env.DB.prepare(
			'SELECT COUNT(*) AS count FROM c15t_consent WHERE subjectId = ?',
		)
			.bind('sub_3jv6z8n4q9')
			.first<{ count: number }>();
		expect(receipts?.count).toBe(1);
	});

	it('recovers a concurrent RPC consent after c15t clamps its event time', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');
		const input = {
			type: body.consent.type,
			documentSnapshotToken: body.consent.documentSnapshotToken,
			subjectId: 'sub_5jv6z8n4q9',
			domain: 'new-rpc.example',
			givenAt: Date.now() + 10 * 60 * 1_000,
		};

		const receipts = await Promise.all([
			recordLegalConsent(env, input),
			recordLegalConsent(env, input),
		]);

		expect(receipts[0]?.consentId).toBe(receipts[1]?.consentId);
		const stored = await env.DB.prepare(
			'SELECT COUNT(*) AS count FROM c15t_consent WHERE subjectId = ?',
		)
			.bind(input.subjectId)
			.first<{ count: number }>();
		expect(stored?.count).toBe(1);
	});

	it('does not create c15t identity state for an invalid consent body', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');

		const response = await submitConsent(body.consent, {
			subjectId: 'invalid',
			domain: 'orphan.example',
		});

		expect(response.status).toBe(400);
		const identities = await env.DB.prepare(
			`SELECT
				(SELECT COUNT(*) FROM c15t_subject WHERE id = ?) AS subjects,
				(SELECT COUNT(*) FROM c15t_domain WHERE name = ?) AS domains`,
		)
			.bind('invalid', 'orphan.example')
			.first<{ subjects: number; domains: number }>();
		expect(identities).toEqual({ subjects: 0, domains: 0 });
	});

	it('does not create c15t identity state for an expired capability', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');
		vi.useFakeTimers();
		vi.setSystemTime(Date.now() + 16 * 60 * 1_000);

		try {
			const response = await submitConsentDirectly(body.consent, {
				subjectId: 'sub_4jv6z8n4q9',
				domain: 'expired.example',
			});
			expect(response.status).toBe(409);
		} finally {
			vi.useRealTimers();
		}
		const identities = await env.DB.prepare(
			`SELECT
				(SELECT COUNT(*) FROM c15t_subject WHERE id = ?) AS subjects,
				(SELECT COUNT(*) FROM c15t_domain WHERE name = ?) AS domains`,
		)
			.bind('sub_4jv6z8n4q9', 'expired.example')
			.first<{ subjects: number; domains: number }>();
		expect(identities).toEqual({ subjects: 0, domains: 0 });
	});

	it('retires the active c15t policy with its EdgeCMS release', async () => {
		const seeded = await seedActiveLegalDocument();

		const result = await retireLegalRelease(seeded.release.id);

		expect(result.ok).toBe(true);
		const policy = await env.DB.prepare(
			'SELECT isActive FROM c15t_consentPolicy',
		).first<{ isActive: number }>();
		expect(policy?.isActive).toBe(0);
	});

	it('enforces release transition preconditions inside the D1 batch', async () => {
		const seeded = await seedActiveLegalDocument();

		await expect(
			activateLegalReleaseWithConsentPolicy(env, seeded.release.id),
		).resolves.toBeUndefined();
		await retireLegalRelease(seeded.release.id);
		await expect(
			activateLegalReleaseWithConsentPolicy(env, seeded.release.id),
		).rejects.toMatchObject({ name: 'LEGAL_RELEASE_NOT_ACTIVATABLE' });
		await expect(
			retireLegalReleaseWithConsentPolicy(env, seeded.release.id),
		).rejects.toMatchObject({ name: 'LEGAL_RELEASE_NOT_RETIRABLE' });
		await markLegalReleaseFailed(seeded.release.id, 'late workflow failure');
		const release = await env.DB.prepare(
			'SELECT status, failureReason FROM legal_releases WHERE id = ?',
		)
			.bind(seeded.release.id)
			.first<{ status: string; failureReason: string | null }>();
		expect(release).toEqual({ status: 'retired', failureReason: null });
	});

	it('returns a fresh consent capability when the active document is revalidated', async () => {
		const { body, seeded } = await activeLegalDocument();
		const response = await documentLoader({
			request: new Request(
				`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/${seeded.locale}`,
				{ headers: { 'If-None-Match': `"${body.releaseHash}"` } },
			),
			params: { slug: seeded.document.slug, locale: seeded.locale },
		} as never);

		expect(response.status).toBe(200);
		expect(response.headers.get('cache-control')).toBe('private, no-store');
		await expect(response.json()).resolves.toMatchObject({
			consent: {
				documentSnapshotToken: expect.any(String),
			},
		});
	});

	it('keeps expiring consent capabilities out of immutable evidence', async () => {
		const { seeded } = await activeLegalDocument();
		const response = await releaseLoader({
			request: new Request(
				`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/${seeded.locale}/releases/${seeded.signed.releaseHash}`,
			),
			params: {
				slug: seeded.document.slug,
				locale: seeded.locale,
				releaseHash: seeded.signed.releaseHash,
			},
		} as never);

		expect(response.headers.get('cache-control')).toContain('immutable');
		expect(await response.json()).not.toHaveProperty('consent');
	});

	it('registers consent policy state for a release that predates the migration', async () => {
		const seeded = await seedActiveLegalDocument();
		await env.DB.prepare('DELETE FROM c15t_consentPolicy').run();

		const response = await documentLoader({
			request: new Request(
				`https://cms.test/edge-cms/public/legal/${seeded.document.slug}/${seeded.locale}`,
			),
			params: { slug: seeded.document.slug, locale: seeded.locale },
		} as never);

		expect(response.status).toBe(200);
		const policy = await env.DB.prepare(
			'SELECT hash, isActive FROM c15t_consentPolicy',
		).first<{ hash: string; isActive: number }>();
		expect(policy).toMatchObject({
			hash: expect.stringMatching(/^[a-f0-9]{64}$/u),
			isActive: 1,
		});
		expect(policy?.hash).not.toBe(seeded.signed.releaseHash);
	});

	it('stores append-only acceptance evidence against the rendered release', async () => {
		const { body, seeded } = await activeLegalDocument();
		expect(body.consent).toBeDefined();
		if (!body.consent) return;
		const activePolicy = await env.DB.prepare(
			'SELECT hash FROM c15t_consentPolicy WHERE isActive = 1',
		).first<{ hash: string }>();
		expect(activePolicy).toBeDefined();
		if (!activePolicy) return;

		const response = await submitConsent(body.consent, {
			externalSubjectId: 'user_42',
			identityProvider: 'edgecms-test',
			metadata: { flow: 'signup' },
			givenAt: 1,
		});

		expect(response.status).toBe(200);
		const receipt = (await response.json()) as Record<string, unknown>;
		expect(receipt).toMatchObject({
			subjectId: 'sub_2jv6z8n4q9',
			consentId: expect.stringMatching(/^cns_/u),
			domain: 'client.example',
			type: body.consent.type,
			metadata: {
				flow: 'signup',
				edgecmsLegalDocument: { clientGivenAt: 1 },
			},
		});
		expect(Date.parse(receipt.givenAt as string)).toBeGreaterThan(1_000);
		const status = await SELF.fetch(
			`https://cms.test/edge-cms/consent/subjects/sub_2jv6z8n4q9?type=${body.consent.type}`,
			{ headers: { Origin: 'https://cms.test' } },
		);
		expect(status.status).toBe(200);
		await expect(status.json()).resolves.toMatchObject({
			isValid: true,
			consents: [
				{
					type: body.consent.type,
					policyHash: activePolicy.hash,
					isLatestPolicy: true,
				},
			],
		});
		const evidence = await env.DB.prepare(
			`SELECT consent.subjectId, policy.hash, policy.version
			 FROM c15t_consent AS consent
			 JOIN c15t_consentPolicy AS policy ON policy.id = consent.policyId`,
		).first<{
			subjectId: string;
			hash: string;
			version: string;
		}>();
		expect(evidence).toMatchObject({
			subjectId: 'sub_2jv6z8n4q9',
			hash: activePolicy.hash,
			version: seeded.release.version,
		});
	});

	it('rejects a forged document snapshot without writing consent', async () => {
		const { body } = await activeLegalDocument();
		expect(body.consent).toBeDefined();
		if (!body.consent) return;

		const response = await submitConsent(body.consent, {
			documentSnapshotToken: 'not.a.signature',
		});

		expect(response.status).toBe(409);
		await expect(response.json()).resolves.toMatchObject({
			code: 'LEGAL_DOCUMENT_SNAPSHOT_INVALID',
		});
		const row = await env.DB.prepare(
			'SELECT COUNT(*) AS count FROM c15t_consent',
		).first<{ count: number }>();
		expect(row?.count).toBe(0);
	});

	it('keeps separate acceptance events for the same subject', async () => {
		const { body } = await activeLegalDocument();
		expect(body.consent).toBeDefined();
		if (!body.consent) return;

		const firstGivenAt = Date.now() - 1_000;
		await recordLegalConsent(env, {
			type: body.consent.type,
			documentSnapshotToken: body.consent.documentSnapshotToken,
			subjectId: 'sub_2jv6z8n4q9',
			domain: 'client.example',
			givenAt: firstGivenAt,
		});
		await recordLegalConsent(env, {
			type: body.consent.type,
			documentSnapshotToken: body.consent.documentSnapshotToken,
			subjectId: 'sub_2jv6z8n4q9',
			domain: 'client.example',
			givenAt: firstGivenAt + 1_001,
		});

		const row = await env.DB.prepare(
			'SELECT COUNT(*) AS count FROM c15t_consent WHERE subjectId = ?',
		)
			.bind('sub_2jv6z8n4q9')
			.first<{ count: number }>();
		expect(row?.count).toBe(2);
	});

	it('supports browser preflight for consent writes', async () => {
		const response = await SELF.fetch(
			'https://cms.test/edge-cms/consent/subjects',
			{
				method: 'OPTIONS',
				headers: {
					Origin: 'https://cms.test',
					'Access-Control-Request-Method': 'POST',
				},
			},
		);

		expect(response.status).toBe(204);
		expect(response.headers.get('access-control-allow-origin')).toBe(
			'https://cms.test',
		);
		expect(response.headers.get('access-control-allow-methods')).toContain(
			'POST',
		);
	});

	it('does not expose the c15t subject directory or external-id lookup', async () => {
		for (const path of [
			'/edge-cms/consent/subjects',
			'/edge-cms/consent/consents/check?externalId=user_42',
		]) {
			const response = await SELF.fetch(`https://cms.test${path}`, {
				headers: { Origin: 'https://cms.test' },
			});
			expect(response.status).toBe(404);
		}
	});

	it('does not let a public consent submission link an external identity', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');
		await submitConsent(body.consent, {
			externalSubjectId: 'user_42',
			identityProvider: 'edgecms-test',
		});

		const response = await SELF.fetch(
			`https://cms.test/edge-cms/consent/subjects/sub_2jv6z8n4q9?type=${body.consent.type}`,
			{ headers: { Origin: 'https://cms.test' } },
		);
		const status = (await response.json()) as {
			subject: Record<string, unknown>;
		};
		expect(status.subject).not.toHaveProperty('externalId');
		const subject = await env.DB.prepare(
			'SELECT externalId, identityProvider FROM c15t_subject WHERE id = ?',
		)
			.bind('sub_2jv6z8n4q9')
			.first<{ externalId: string | null; identityProvider: string }>();
		expect(subject).toEqual({ externalId: null, identityProvider: 'anonymous' });
	});

	it('ignores c15t consent controls outside the public legal contract', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');

		const response = await submitConsent(body.consent, {
			preferences: { legal: false },
			consentAction: 'necessary',
			jurisdictionModel: 'opt-out',
			tcString: 'forged-tc-string',
			uiSource: 'forged-ui',
		});

		expect(response.status).toBe(200);
		await expect(response.clone().json()).resolves.not.toHaveProperty(
			'appliedPreferences',
		);
		const receipt = await env.DB.prepare(
			`SELECT jurisdictionModel, tcString, uiSource, consentAction
			 FROM c15t_consent WHERE subjectId = ?`,
		)
			.bind('sub_2jv6z8n4q9')
			.first<{
				jurisdictionModel: string | null;
				tcString: string | null;
				uiSource: string | null;
				consentAction: string | null;
			}>();
		expect(receipt).toEqual({
			jurisdictionModel: null,
			tcString: null,
			uiSource: null,
			consentAction: null,
		});
	});

	it('returns 429 when the public consent write limit is exhausted', async () => {
		const runtimeEnv = {
			TRUSTED_ORIGINS: env.TRUSTED_ORIGINS,
			LEGAL_CONSENT_RATE_LIMITER: {
				limit: () => Promise.resolve({ success: false }),
			},
		} as Env;
		const response = await handleConsentRequest(
			new Request('https://cms.test/edge-cms/consent/subjects', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					Origin: 'https://cms.test',
					'CF-Connecting-IP': '192.0.2.1',
				},
				body: '{}',
			}),
			runtimeEnv,
		);

		expect(response.status).toBe(429);
		expect(response.headers.get('retry-after')).toBe('60');
		expect(response.headers.get('access-control-allow-origin')).toBe(
			'https://cms.test',
		);
		await expect(response.json()).resolves.toMatchObject({
			code: 'LEGAL_CONSENT_RATE_LIMITED',
		});
	});

	it('rejects oversized consent submissions', async () => {
		const { body } = await activeLegalDocument();
		if (!body.consent) throw new Error('Expected consent capability');

		const response = await submitConsent(body.consent, {
			metadata: { padding: 'x'.repeat(70_000) },
		});

		expect(response.status).toBe(413);
		await expect(response.json()).resolves.toMatchObject({
			code: 'CONSENT_REQUEST_TOO_LARGE',
		});
	});

	it('stops reading a chunked consent submission at the size limit', async () => {
		let cancelled = false;
		let closeTimer: ReturnType<typeof setTimeout> | undefined;
		const body = new ReadableStream<Uint8Array>({
			start(controller) {
				controller.enqueue(new Uint8Array(64 * 1024 + 1));
				closeTimer = setTimeout(() => controller.close(), 10);
			},
			cancel() {
				cancelled = true;
				if (closeTimer) clearTimeout(closeTimer);
			},
		});
		const request = new Request(
			'https://cms.test/edge-cms/consent/subjects',
			{
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					Origin: 'https://cms.test',
				},
				body,
			} as RequestInit,
		);

		const response = await handleConsentRequest(request, env);

		expect(response.status).toBe(413);
		expect(cancelled).toBe(true);
	});

	it('exposes c15t health status', async () => {
		const response = await SELF.fetch(
			'https://cms.test/edge-cms/consent/status',
			{ headers: { Origin: 'https://cms.test' } },
		);

		expect(response.status).toBe(200);
		await expect(response.json()).resolves.toMatchObject({
			version: expect.any(String),
			timestamp: expect.any(String),
		});
	});

	it('rejects consent types outside signed legal documents', async () => {
		const response = await SELF.fetch(
			'https://cms.test/edge-cms/consent/subjects',
			{
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					Origin: 'https://cms.test',
				},
				body: JSON.stringify({
					type: 'cookie_banner',
					subjectId: 'sub_5jv6z8n4q9',
					domain: 'client.example',
					givenAt: Date.now(),
					preferences: { necessary: true },
				}),
			},
		);

		expect(response.status).toBe(422);
		expect(response.headers.get('access-control-allow-origin')).toBe(
			'https://cms.test',
		);
		await expect(response.json()).resolves.toMatchObject({
			code: 'LEGAL_CONSENT_ONLY',
		});
	});

	it('does not expose c15t mutation routes outside legal acceptance', async () => {
		const response = await SELF.fetch(
			'https://cms.test/edge-cms/consent/subjects/sub_2jv6z8n4q9',
			{
				method: 'PATCH',
				headers: {
					'Content-Type': 'application/json',
					Origin: 'https://cms.test',
				},
				body: JSON.stringify({ externalSubjectId: 'user_42' }),
			},
		);

		expect(response.status).toBe(405);
		expect(response.headers.get('allow')).toBe('GET, POST, OPTIONS');
	});
});
